### ISSUE TITLE
validate sintax

### ISSUE THREAD

**Issue by linediconsine** [jacobbednarz/csp-validator#1]
hi, I tested in a complex scenario this code.
In my test this not report syntax (or in wrong position) value.

I modified the url domain :

Content-Security-Policy:
script-src 'self' _.domain1.com *.domain11.com *.domain111.com *.domain1111.com *.domain11111.com *.domain11112.com *.domain111112.com
 'unsafe-eval' *.unodue.com *.unoduetre.com *.unoduetre1.com *.unoduetre21.com *.un1oduetre221.com *.testun1oduetre221.com 
https://testun1oduetre221.com *.testun1oduetre221c.com *.atestun1oduetre221.com *.atestun1oduetre221.net  *.atestun1oduetreaa221.net *.bananaatestun1oduetreaa221.net *.bananana.it *.bananansa.it  *.babananansa.it  *.babananananasa.it; img-src 'self' data: *.babananananaanananasa.it *.babananananaanananasa.it *.bababananananaanananasa.it  *.bababan.net *.bababan.banana.net *.bananananana01.jp *.bananananana02.jp *.bananananana03.jp *.banananana04.com data: *.banananana05.com *.banananana06.com .banananana07.fr *.banananana07.com *.banananana07.co.uk *.banananana071.net *.facebook.com *.2bananana7.net *.banananan09.com *. banananan09.com *.banananan10.com *.banananan11.com *.banananan11.com; frame-src 'self' *.googlesyndication.com bananacampaigns.com *.bananacampaigns.com *.doubleclickbanana.net https://_.youtube.com http://*.youtube.com *.appbanana.com; media-src *.bananacampaigns.com; font-src 'self' data: *.banana.com *.usbananana.net; options eval-script; default-src 'self'; style-src 'self' *.bananaassets.com *.virtualbanana.net *.doublebanana.net *.bananasyndication.com *.pubbanana.com *.banana.com *.tradebanana.com *.bananananana111.com 'unsafe-inline'

Thanks

**Comment by jacobbednarz** [comment]
Are you able to provide some further details on the issues you are seeing? Perhaps with examples or screenshots?

Thanks!

**Comment by linediconsine** [comment]
I read :
The 'option' directive has been replaced with 'unsafe-inline' and 'unsafe-eval' source expression for the 'script-src' and 'style-src' directives. Please use those directives instead, as 'options' has no effect.

and highlight some different js on different pages.  

I hope this help and thanks for you feedback 

PS: sorry I cannot share the page or screenshot here and I changed the referred domain to similar

Thanks

**Comment by jacobbednarz** [comment]
> The 'option' directive has been replaced with 'unsafe-inline' and 'unsafe-eval' source expression for the 'script-src' and 'style-src' directives. Please use those directives instead, as 'options' has no effect.

Where did you read this? I have just gone through the spec for CSP1 and CSP2 and wasn't able to find what you were referring to.

> PS: sorry I cannot share the page or screenshot here and I changed the referred domain to similar

I'm happy if you'd like to email it to me and I can take a look?

I'm also not sure if domains like `.domain1.com` are valid resources.

**Comment by linediconsine** [comment]
Thanks,

Could you please give me an email ?

Thanks

**Comment by jacobbednarz** [comment]
jacob.bednarz at gmail.com
